import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Audit & Reference',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'category',
          label: 'Backend',
          link: { type: 'generated-index' },
          items: [
            'audit/backend/overview',
            'audit/backend/getting-started',
            'audit/backend/module-catalogue',
            'audit/backend/data-model',
            'audit/backend/coding-standards',
            'audit/backend/testing',
          ],
        },
        {
          type: 'category',
          label: 'Infrastructure',
          link: { type: 'generated-index' },
          items: [
            'audit/infrastructure/overview',
            'audit/infrastructure/environments',
            'audit/infrastructure/deployment',
            'audit/infrastructure/secrets',
            'audit/infrastructure/dr-and-backups',
          ],
        },
        {
          type: 'category',
          label: 'Operations',
          link: { type: 'generated-index' },
          items: [
            {
              type: 'category',
              label: 'Runbooks',
              items: [
                'audit/operations/runbooks/sqs-backlog',
                'audit/operations/runbooks/ws-gateway-crash',
                'audit/operations/runbooks/prisma-migration-drift',
                'audit/operations/runbooks/llm-provider-outage',
                'audit/operations/runbooks/stripe-webhook-failure',
              ],
            },
            {
              type: 'category',
              label: 'Incidents',
              items: [
                'audit/operations/incidents/2026-04-email-ai-loop',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Security',
          link: { type: 'generated-index' },
          items: ['audit/security/overview'],
        },
        {
          type: 'category',
          label: 'Contributing',
          link: { type: 'generated-index' },
          items: ['audit/contributing/branching'],
        },
      ],
    },
    // Existing frontend integration docs
    {type: 'autogenerated', dirName: 'beehive'},
    {type: 'autogenerated', dirName: 'automations'},
    {type: 'autogenerated', dirName: 'channels-integration'},
    {type: 'autogenerated', dirName: 'copilot'},
  ],
};

export default sidebars;
